name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --save-dev
      - run: npm run build
        env:
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: ".next/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
      - name: Clear Cloudflare cache
        uses: Cyb3r-Jak3/action-cloudflare-cache@v1.1.0
        with:
          # Zone is required by both methods
          zone: ${{ secrets.CLOUDFLARE_ZONE }}

          # Using API Token
          api_token: ${{ secrets.CLOUDFLARE_TOKEN }}